In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np

In [2]:
dataset = pd.read_csv("AmesHousing.csv")

# Feature Engineering

### step1 : Only Conceptual (not coding)

So First we focus of these questions 

Q1). How big is the house?   # mainly dependent on Gr Liv Area 
Q2). How old is it?          # Created new feature House Age 
Q3). How luxurious is it?    # Quality Size Score significantly tells this 
Q4). How functional is it?   # Has Basement , Has Garage , Total Bathrooms 
Q5). How much usable space does it have?   # Total finished Area

House price mainly depends on how big the house is, how old it is, how good and luxurious it looks, how well it works for living, and how much usable space it has. I create features in the data to represent these things, just like how a real buyer thinks before buying a house.

As Year Build and Yr Sold both togetherly signifies the Age of house

In [3]:
dataset['House Age'] = dataset['Yr Sold'] - dataset['Year Built']   # House Age is better than Year Built because it shows the how much the house is old

How “fresh” is the house?

In [4]:
dataset['Year since Remodel'] = dataset['Yr Sold'] - dataset['Year Remod/Add']

Has the house ever been significantly updated?

In [5]:
dataset['Is_Remodeled'] = (dataset['Year Built'] != dataset['Year Remod/Add']).astype(int)

How much space can i Live in ?

In [6]:
dataset['Total Living Area'] = dataset['Gr Liv Area']+dataset['Total Bsmt SF']

How much of the house is already usable without renovation?

In [7]:
dataset['Total Finished Area'] = dataset['Gr Liv Area'] + dataset['BsmtFin SF 1'] + dataset['BsmtFin SF 2']

Does the house even have a basement ?

In [8]:
dataset['Has_Basement'] = dataset['Total Bsmt SF'].apply(lambda x: 1 if x > 0 else 0)

Why is Has_Basement useful even though you already have basement area?
=> Has_Basement captures the presence of a basement, whereas basement area only measures size; zero area does not clearly indicate absence.

How many functional bathrooms does the house have?

In [9]:
dataset['Total Bathrooms'] = dataset['Bsmt Full Bath']+0.5*dataset['Bsmt Half Bath']+dataset['Full Bath']+0.5*dataset['Half Bath']

Garage age

In [10]:
dataset['Garage Age'] = dataset['Yr Sold'] - dataset['Garage Yr Blt']

We Check the Garage Age only if Garage exists

In [11]:
dataset['Garage Exists'] = dataset['Garage Area'].apply(lambda x: 1 if x>0 else 0)

is the house both big and high Quality ?

In [12]:
dataset['Quality_size_score'] = dataset['Overall Qual']*dataset['Gr Liv Area']

How many non bedrooms in the house ?

In [13]:
dataset['Non_Bedroom_Rooms'] = dataset['TotRms AbvGrd'] - dataset['Bedroom AbvGr']

In [14]:
dataset[['Non_Bedroom_Rooms','TotRms AbvGrd','Bedroom AbvGr','SalePrice']].corr()

                   Non_Bedroom_Rooms  TotRms AbvGrd  Bedroom AbvGr  SalePrice
Non_Bedroom_Rooms           1.000000       0.856459       0.194115   0.556460
TotRms AbvGrd               0.856459       1.000000       0.672647   0.495474
Bedroom AbvGr               0.194115       0.672647       1.000000   0.143913
SalePrice                   0.556460       0.495474       0.143913   1.000000

In [15]:
dataset[['1st Flr SF','Gr Liv Area']].corr()

             1st Flr SF  Gr Liv Area
1st Flr SF     1.000000     0.562166
Gr Liv Area    0.562166     1.000000

In [ ]:
dataset.select_dtypes(include = ['int64','float64']).columns 

dataset[['Mas Vnr Area','1st Flr SF', '2nd Flr SF', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch' , 'SalePrice']].corr()